## MNIST classiffication of alphabets (1-10) classes using Incremental Extreme Machine learning

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import keras
from keras.models import Sequential
from keras.datasets import mnist
from keras.layers import Dense
from keras.optimizers import Adam
import random
import keras
import keras.utils
from keras.utils.np_utils import to_categorical 
from keras import utils as np_utils
from sklearn.preprocessing import OneHotEncoder 
from sklearn.metrics import accuracy_score
import time




Using TensorFlow backend.


In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data() #-----------------loading mnist dataset

In [11]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape[0])
print(y_train.shape)
print(y_test.shape)
print(y_train[1])
print(y_test[1:100])

(60000, 28, 28)
(10000, 28, 28)
60000
(60000, 10)
(10000, 10)
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0

In [10]:
y_train = to_categorical(y_train, 10)#-------------------converting values of mnist with 10 classes
y_test = to_categorical(y_test, 10)

In [98]:
#Each image has Intensity from 0 to 255
X_train = X_train
X_test = X_test

In [99]:
                                                #we must change the shape of the images to 1d array(28*28)
                                                    #for multipication 1*784
num_pixels = 784
X_train = X_train.reshape(X_train.shape[0],
                         num_pixels)
X_test = X_test.reshape(X_test.shape[0],
                         num_pixels)
print(X_train.shape)



(60000, 784)


In [100]:
print(y_train.shape)
predicted_output=np.zeros([1,10])
print(predicted_output)
acc=0

(60000, 10)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [101]:
print(y_train.shape)
predicted_output=np.zeros([1,10])
print(predicted_output)
acc=0

(60000, 10)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [102]:
start = time.time()
l=0
l_max=100 #-----------------------------------settting number of neurons
beta=0
error=0
for i in range(l_max):
    
    
    
    
    
    if(acc<90):
        weights = np.random.rand(784,i)*100#------------------------------creating random weight matrix== features X num_neuron #nearon should be greater than feature
        weights_transpose = np.transpose(weights)
        weights.shape
        h_new = np.dot(X_train,weights)#--------------------------finding value of h
        h_inv = np.linalg.pinv(h_new)#-----------------------------finding pseudo inverse of h
    
        beta = np.dot(h_inv, y_train)#------------------finding beta
    #print(beta.shape)
    #print(h_new.shape)
        predicted_output = np.dot(h_new,beta)#--------------------predicted output
        #error = y_train - predicted_output
        #print(predicted_output)
        
        
    #print(predicted_output.shape)

    k=0
    j=0
    for k in range(60000):
        for j in range(10):
            max_item=max(predicted_output[k][:])#------------------------------changing the maximum value as 1 and other as 0
            if(predicted_output[k][j]==max_item):
                predicted_output[k][j]=1
    
            else:
                predicted_output[k][j]=0
        
   # print(predicted_output[i][:])    
   # print(predicted_output.shape)  
        #print(y_train)
    acc = accuracy_score(predicted_output,y_train)#-----------------------------FInding accuracy
    print("Accuracy number", i, "is", + acc*100, "%")      
end = time.time()
print("Time elapsed",end - start)
    #print(error)
    
    #print(h_inv.shape)
    #print(h_new.shape)
    #print(beta)
    #print(weights.shape)
#print(error[1][9])

Accuracy number 0 is 9.871666666666666 %
Accuracy number 1 is 9.871666666666666 %
Accuracy number 2 is 20.68 %
Accuracy number 3 is 29.21166666666667 %
Accuracy number 4 is 24.078333333333333 %
Accuracy number 5 is 38.96 %
Accuracy number 6 is 36.21666666666667 %
Accuracy number 7 is 34.43333333333333 %
Accuracy number 8 is 43.53666666666667 %
Accuracy number 9 is 48.513333333333335 %
Accuracy number 10 is 48.141666666666666 %
Accuracy number 11 is 52.06833333333334 %
Accuracy number 12 is 53.803333333333335 %
Accuracy number 13 is 54.50833333333334 %
Accuracy number 14 is 54.635 %
Accuracy number 15 is 53.381666666666675 %
Accuracy number 16 is 59.93333333333334 %
Accuracy number 17 is 58.17 %
Accuracy number 18 is 56.40666666666667 %
Accuracy number 19 is 58.60666666666666 %
Accuracy number 20 is 61.083333333333336 %
Accuracy number 21 is 65.11333333333333 %
Accuracy number 22 is 63.73833333333333 %
Accuracy number 23 is 65.19 %
Accuracy number 24 is 63.915 %
Accuracy number 25 is 67

In [77]:
#print(error[1])
#print(predicted_output[1])
#print(y_train.size)
#print(beta)


In [78]:
#h_new = np.dot(X_train,weights)
#h_new.shape

In [79]:
#h_reshaped = np.reshape(h, (l, 784))
#h_inv = np.linalg.pinv(h_new)
#print(h_inv.shape)

In [80]:
#beta = np.dot(h_inv, y_train)

In [81]:
#print(beta)


In [82]:
#predicted_output= np.dot(h_new, beta) #----------------------------------------------------predicting value 
#print(predicted_output.shape)

In [83]:
#[1][:])

In [84]:
#acc = accuracy_score(error,y_train)#-----------------------------FInding accuracy
#print("Accuracy is", + acc*100, "%")